// src/steps/selectInclusionsStep/SelectInclusionsStep.svelte
<script lang="ts">
  import { css } from "goober";
  import { onMount } from "svelte";

  import {
    fetchAllEntities,
    flipIfExistsInTargetShown,
  } from "~/modules/allEntities/allEntitiesActions";
  import * as allEntitiesSelectors from "~/modules/allEntities/allEntitiesSelectors";
  import { navigateToRoute } from "~/modules/app/navigateToRoute";
  import { updateActiveWorkspaceId } from "~/modules/workspaces/workspacesActions";
  import {
    activeWorkspaceIdSelector,
    includedSourceWorkspacesSelector,
  } from "~/modules/workspaces/workspacesSelectors";
  import { dispatchAction, selectorToStore } from "~/redux/reduxToStore";
  import {
    FetchStatus,
    RoutePath,
    ToolAction,
    type WorkspaceModel,
  } from "~/typeDefs";
  import { capitalize } from "~/utilities/textTransforms";

  import Loader from "~/components/Loader.svelte";
  import NavigationButtonsRow from "~/components/NavigationButtonsRow.svelte";
  import Toggle from "~/components/Toggle.svelte";
  import WorkspaceSelect from "~/components/WorkspaceSelect.svelte";

  import ClientsInclusionsPanel from "./ClientsInclusionsPanel.svelte";
  import HelpForToolAction from "./HelpForToolAction.svelte";
  import NoSelectionsDialog from "./NoSelectionsDialog.svelte";
  import ProjectsInclusionsPanel from "./ProjectsInclusionsPanel.svelte";
  import TagsInclusionsPanel from "./TagsInclusionsPanel.svelte";
  import TasksInclusionsPanel from "./TasksInclusionsPanel.svelte";
  import TimeEntriesInclusionsPanel from "./TimeEntriesInclusionsPanel.svelte";

  const activeWorkspaceId = selectorToStore(activeWorkspaceIdSelector);

  const includedSourceWorkspaces = selectorToStore(
    includedSourceWorkspacesSelector,
  );

  const areExistsInTargetShown = selectorToStore(
    allEntitiesSelectors.areExistsInTargetShownSelector,
  );

  const entityGroupInProcessDisplay = selectorToStore(
    allEntitiesSelectors.entityGroupInProcessDisplaySelector,
  );

  const fetchAllFetchStatus = selectorToStore(
    allEntitiesSelectors.fetchAllFetchStatusSelector,
  );

  const toolAction = selectorToStore(allEntitiesSelectors.toolActionSelector);

  const totalIncludedRecordsCount = selectorToStore(
    allEntitiesSelectors.totalIncludedRecordsCountSelector,
  );

  let isNoSelectionsDialogOpen: boolean = false;

  onMount(() => {
    if ($fetchAllFetchStatus === FetchStatus.Pending) {
      dispatchAction(fetchAllEntities.request());
    }

    if (!$areExistsInTargetShown) {
      dispatchAction(flipIfExistsInTargetShown());
    }
  });

  function handleSelectActiveWorkspace(
    event: CustomEvent<WorkspaceModel>,
  ): void {
    dispatchAction(updateActiveWorkspaceId(event.detail.id));
  }

  function handleShowExistingToggle(): void {
    dispatchAction(flipIfExistsInTargetShown());
  }

  function handleBackClick(): void {
    navigateToRoute(RoutePath.SelectWorkspaces);
  }

  function handleNextClick(): void {
    if ($totalIncludedRecordsCount === 0) {
      isNoSelectionsDialogOpen = true;
    } else {
      navigateToRoute(RoutePath.PerformToolAction);
    }
  }

  function handleRefreshClick(): void {
    dispatchAction(fetchAllEntities.request());
  }

  const workspacesFieldStyleClass = css`
    display: inline-block;
    margin-bottom: 1rem;
    position: relative;
    width: 100%;

    label {
      font-size: 1rem;
      font-weight: var(--font-weight-bold);
    }

    &:hover,
    &:focus {
      select {
        color: var(--color-primary);
      }

      span {
        border-top-color: var(--color-primary);
      }
    }
  `;
</script>

<main>
  <h1>Step 4: Select Records to {capitalize($toolAction)}</h1>

  <HelpForToolAction toolAction={$toolAction} />

  {#if $fetchAllFetchStatus === FetchStatus.Success}
    <div class={workspacesFieldStyleClass}>
      <label for="active-workspace">Active Workspace</label>
      <WorkspaceSelect
        id="active-workspace"
        workspaces={$includedSourceWorkspaces}
        value={$activeWorkspaceId}
        on:select={handleSelectActiveWorkspace}
      />
    </div>

    {#if $toolAction === ToolAction.Transfer}
      <div>
        <label for="show-existing-toggle">
          Show records that already exist in target?
        </label>
        <Toggle
          id="show-existing-toggle"
          style="background-color: var(--color-white);"
          toggled={$areExistsInTargetShown}
          on:toggle={handleShowExistingToggle}
        />
      </div>
    {/if}

    <h2>Workspace Records</h2>
    <div style="margin-bottom: 2rem;">
      <ClientsInclusionsPanel />
      <TagsInclusionsPanel />
      <ProjectsInclusionsPanel />
      <TasksInclusionsPanel />
      <TimeEntriesInclusionsPanel />
    </div>
  {:else}
    <Loader>Fetching {$entityGroupInProcessDisplay}, please wait...</Loader>
  {/if}

  <NavigationButtonsRow
    disabled={$fetchAllFetchStatus === FetchStatus.InProcess}
    refreshLabel="refresh"
    on:back={handleBackClick}
    on:next={handleNextClick}
    on:refresh={handleRefreshClick}
  />

  <NoSelectionsDialog
    bind:open={isNoSelectionsDialogOpen}
    toolAction={$toolAction}
  />
</main>

// src/allEntities/selectInclusionsStep/SelectInclusionsStep.tsx
import { push } from "connected-react-router";
import React from "react";
import { connect } from "react-redux";
import { PayloadActionCreator } from "typesafe-actions";

import {
  fetchAllEntities,
  flipIfExistsInTargetShown,
} from "~/allEntities/allEntitiesActions";
import {
  areExistsInTargetShownSelector,
  entityGroupInProcessDisplaySelector,
  fetchAllFetchStatusSelector,
  toolActionSelector,
  totalIncludedRecordsCountSelector,
} from "~/allEntities/allEntitiesSelectors";
import {
  Button,
  Loader,
  LoadingMessage,
  NavigationButtonsRow,
} from "~/components";
import { FetchStatus, ReduxState, RoutePath, ToolAction } from "~/typeDefs";
import { capitalize } from "~/utils";
import { activeWorkspaceIdSelector } from "~/workspaces/workspacesSelectors";

import ActiveWorkspaceSelect from "./ActiveWorkspaceSelect";
import InclusionsPanelsAccordion from "./InclusionsPanelsAccordion";
import NoSelectionsModal from "./NoSelectionsModal";
import SelectInclusionsHelpByAction from "./SelectInclusionsHelpByAction";
import ShowExistingToggle from "./ShowExistingToggle";

interface ConnectStateProps {
  activeWorkspaceId: string;
  areExistsInTargetShown: boolean;
  entityGroupInProcessDisplay: string;
  fetchAllFetchStatus: FetchStatus;
  toolAction: ToolAction;
  totalIncludedRecordsCount: number;
}

interface ConnectDispatchProps {
  onFetchAllEntities: PayloadActionCreator<string, void>;
  onFlipIfExistsInTargetShown: PayloadActionCreator<string, void>;
  onPush: (path: RoutePath) => void;
}

type Props = ConnectStateProps & ConnectDispatchProps;

export const SelectInclusionsStepComponent: React.FC<Props> = (props) => {
  const [isErrorModalOpen, setIsErrorModalOpen] =
    React.useState<boolean>(false);

  React.useEffect(() => {
    if (props.fetchAllFetchStatus === FetchStatus.Pending) {
      props.onFetchAllEntities();
    }

    if (!props.areExistsInTargetShown) {
      props.onFlipIfExistsInTargetShown();
    }
  }, []);

  const handleBackClick = (): void => {
    props.onPush(RoutePath.SelectWorkspaces);
  };

  const handleNextClick = (): void => {
    if (props.totalIncludedRecordsCount === 0) {
      setIsErrorModalOpen(true);
    } else {
      props.onPush(RoutePath.PerformToolAction);
    }
  };

  const handleRefreshClick = (): void => {
    props.onFetchAllEntities();
  };

  const handleShowExistingToggle = (): void => {
    props.onFlipIfExistsInTargetShown();
  };

  const handleCloseModal = (): void => {
    setIsErrorModalOpen(false);
  };

  return (
    <section>
      <h1>Step 4: Select Records to {capitalize(props.toolAction)}</h1>
      <SelectInclusionsHelpByAction toolAction={props.toolAction} />
      {props.fetchAllFetchStatus === FetchStatus.Success ? (
        <>
          <ActiveWorkspaceSelect />
          {props.toolAction === ToolAction.Transfer && (
            <ShowExistingToggle
              isToggled={props.areExistsInTargetShown}
              onToggle={handleShowExistingToggle}
            />
          )}
          <InclusionsPanelsAccordion />
        </>
      ) : (
        <>
          <Loader />
          <LoadingMessage>
            Fetching {props.entityGroupInProcessDisplay}, please wait...
          </LoadingMessage>
        </>
      )}
      <NavigationButtonsRow
        disabled={props.fetchAllFetchStatus === FetchStatus.InProcess}
        onBackClick={handleBackClick}
        onNextClick={handleNextClick}
      >
        <Button
          disabled={props.fetchAllFetchStatus === FetchStatus.InProcess}
          variant="eggplant"
          onClick={handleRefreshClick}
        >
          Refresh
        </Button>
      </NavigationButtonsRow>
      <NoSelectionsModal
        isOpen={isErrorModalOpen}
        toolAction={props.toolAction}
        onClose={handleCloseModal}
      />
    </section>
  );
};

const mapStateToProps = (state: ReduxState): ConnectStateProps => ({
  activeWorkspaceId: activeWorkspaceIdSelector(state),
  areExistsInTargetShown: areExistsInTargetShownSelector(state),
  entityGroupInProcessDisplay: entityGroupInProcessDisplaySelector(state),
  fetchAllFetchStatus: fetchAllFetchStatusSelector(state),
  toolAction: toolActionSelector(state),
  totalIncludedRecordsCount: totalIncludedRecordsCountSelector(state),
});

const mapDispatchToProps: ConnectDispatchProps = {
  onFetchAllEntities: fetchAllEntities.request,
  onFlipIfExistsInTargetShown: flipIfExistsInTargetShown,
  onPush: push,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(SelectInclusionsStepComponent);
