// src/steps/enterApiKeysStep/ApiKeyInputField.svelte
<script lang="ts">
  import { slide } from "svelte/transition";

  import type { ToolHelpDetailsModel } from "~/typeDefs";

  import ExternalLink from "~/components/ExternalLink.svelte";

  export let mapping: string;
  export let toolHelpDetails: ToolHelpDetailsModel;
  export let errorMessage: string | null;
  export let value: string;

  const { toolName, displayName, toolLink } = toolHelpDetails;
</script>

<style>
  input {
    margin-bottom: 2rem;
    padding: 0.5rem;
    width: 100%;
    border: none;
    border-radius: 0.25rem;
    font-family: monospace;
    font-size: 1.25rem;
    box-shadow: var(--elevation-dp2);
  }

  label {
    display: block;
    margin: 0.5rem 0;
    font-size: 1rem;
    font-weight: var(--font-weight-bold);
  }

  [role="alert"] {
    display: block;
    margin-top: -1.5rem;
    color: var(--color-ruby);
    font-weight: var(--font-weight-bold);
  }
</style>

<div>
  <!-- prettier-ignore -->
  <label for={toolName}>
    {displayName} API Key (<ExternalLink href={toolLink} color="var(--color-navy)">find it on your {displayName} profile page</ExternalLink>)
  </label>

  <input
    id={toolName}
    name={mapping}
    type="text"
    autocomplete="off"
    aria-describedby="{toolName}-error"
    aria-required={true}
    aria-invalid={errorMessage !== null}
    bind:value
  />

  {#if errorMessage !== null}
    <span transition:slide={{ duration: 250 }} role="alert">
      {errorMessage}
    </span>
  {/if}
</div>

// src/credentials/enterApiKeysStep/ApiKeyInputField.tsx
import cuid from "cuid";
import React from "react";
import { ExternalLink, styled } from "~/components";
import { ToolHelpDetailsModel } from "~/typeDefs";

const ErrorMessage = styled.div(
  {
    marginTop: "-1.5rem",
  },
  ({ theme }) => ({
    color: theme.colors.error,
    fontWeight: theme.fontWeights.bold,
  }),
);

const Input = styled.input(
  {
    border: "none",
    borderRadius: "0.25rem",
    fontFamily: "monospace",
    fontSize: "1.25rem",
    marginBottom: "2rem",
    padding: "0.5rem",
    width: "100%",
  },
  ({ theme }) => ({
    boxShadow: theme.elevation.dp2,
  }),
);

const Label = styled.label(
  {
    display: "block",
    fontSize: "1rem",
    margin: "0.5rem 0",
  },
  ({ theme }) => ({
    fontWeight: theme.fontWeights.bold,
  }),
);

interface Props extends React.InputHTMLAttributes<HTMLInputElement> {
  mapping: string;
  toolHelpDetails: ToolHelpDetailsModel;
  errorMessage?: string | null;
}

const ApiKeyInputField: React.FC<Props> = ({
  mapping,
  toolHelpDetails,
  errorMessage = null,
  ...props
}) => {
  const inputId = cuid.slug();
  return (
    <>
      <Label htmlFor={inputId}>
        {toolHelpDetails.displayName} API Key (
        <ExternalLink href={toolHelpDetails.toolLink}>
          find it on your {toolHelpDetails.displayName} profile page
        </ExternalLink>
        )
      </Label>
      <Input
        id={inputId}
        name={mapping}
        type="text"
        autoComplete="hidden"
        aria-describedby={`${inputId}Error`}
        aria-required={true}
        aria-invalid={errorMessage !== null}
        {...props}
      />
      <ErrorMessage id={`${inputId}Error`}>{errorMessage}</ErrorMessage>
    </>
  );
};

export default ApiKeyInputField;
