// src/steps/performToolActionStep/PerformToolActionStep.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { slide } from "svelte/transition";

  import {
    createAllEntities,
    deleteAllEntities,
    resetTransferCountsByEntityGroup,
  } from "~/modules/allEntities/allEntitiesActions";
  import {
    includedCountsByEntityGroupSelector,
    pushAllChangesFetchStatusSelector,
    toolActionSelector,
    transferCountsByEntityGroupSelector,
  } from "~/modules/allEntities/allEntitiesSelectors";
  import {
    navigateToWorkflowStep,
    WorkflowStep,
  } from "~/modules/app/workflowStep";
  import { dispatchAction, selectorToStore } from "~/redux/reduxToStore";
  import {
    EntityGroup,
    FetchStatus,
    ToolAction,
    type CountsByEntityGroupModel,
  } from "~/typeDefs";
  import { capitalize } from "~/utilities/textTransforms";

  import HelpDetails from "~/components/HelpDetails.svelte";
  import NavigationButtonsRow from "~/components/NavigationButtonsRow.svelte";

  import ConfirmToolActionDialog from "./ConfirmToolActionDialog.svelte";
  import ProgressBar from "./ProgressBar.svelte";

  const includedCountsByEntityGroup = selectorToStore<CountsByEntityGroupModel>(
    includedCountsByEntityGroupSelector,
  );

  const pushAllChangesFetchStatus = selectorToStore(
    pushAllChangesFetchStatusSelector,
  );

  const toolAction = selectorToStore(toolActionSelector);

  const transferCountsByEntityGroup = selectorToStore(
    transferCountsByEntityGroupSelector,
  );

  let isConfirmToolActionDialogOpen: boolean = false;

  let orderedEntityGroups: EntityGroup[];
  $: orderedEntityGroups = getOrderedEntityGroups($includedCountsByEntityGroup);

  const unsubscribe = pushAllChangesFetchStatus.subscribe((value) => {
    if (value === FetchStatus.Success) {
      navigateToWorkflowStep(WorkflowStep.ToolActionSuccess);
    }
  });

  onMount(() => {
    dispatchAction(resetTransferCountsByEntityGroup());

    return () => {
      unsubscribe();
    };
  });

  function getOrderedEntityGroups(
    countsByEntityGroup: CountsByEntityGroupModel,
  ): EntityGroup[] {
    const entityGroups: EntityGroup[] = [];

    const allOrdered =
      $toolAction === ToolAction.Delete
        ? [
            EntityGroup.TimeEntries,
            EntityGroup.Tasks,
            EntityGroup.Projects,
            EntityGroup.Tags,
            EntityGroup.Clients,
          ]
        : Object.keys(countsByEntityGroup);

    for (const entityGroup of allOrdered) {
      if (countsByEntityGroup[entityGroup] !== 0) {
        entityGroups.push(entityGroup as EntityGroup);
      }
    }

    return entityGroups;
  }

  function handleBackClick(): void {
    navigateToWorkflowStep(WorkflowStep.SelectInclusions);
  }

  const handleNextClick = (): void => {
    isConfirmToolActionDialogOpen = true;
  };

  function handleConfirmClick(): void {
    isConfirmToolActionDialogOpen = false;

    switch ($toolAction) {
      case ToolAction.Delete:
        dispatchAction(deleteAllEntities.request());
        break;

      case ToolAction.Transfer:
        dispatchAction(createAllEntities.request());
        break;

      default:
        break;
    }
  }
</script>

<style>
  ul {
    display: flex;
    flex-direction: column;
    margin: 0;
    padding: 0;
  }

  li {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  li:not(:last-of-type) {
    margin-bottom: 1.5rem;
  }
</style>

<main data-step={WorkflowStep.PerformToolAction}>
  <h1>
    {#if $toolAction === ToolAction.None}
      Step 5: Perform Action
    {:else}
      Step 5: Perform {capitalize($toolAction)} Action
    {/if}
  </h1>

  <HelpDetails>
    <p>
      Press the <strong>Start</strong> button and confirm the action in the dialog.
    </p>

    <p class="note">
      Note: This could take several minutes due to API rate limiting.
    </p>
  </HelpDetails>

  <ul>
    {#each orderedEntityGroups as entityGroup}
      <li transition:slide|local={{ duration: 250 }}>
        <ProgressBar
          {entityGroup}
          completedCount={$transferCountsByEntityGroup[entityGroup]}
          totalCount={$includedCountsByEntityGroup[entityGroup]}
        />
      </li>
    {/each}
  </ul>

  <NavigationButtonsRow
    disabled={$pushAllChangesFetchStatus === FetchStatus.InProcess}
    nextLabel="Start"
    on:back={handleBackClick}
    on:next={handleNextClick}
  />

  <ConfirmToolActionDialog
    bind:open={isConfirmToolActionDialogOpen}
    toolAction={$toolAction}
    on:confirm={handleConfirmClick}
  />
</main>

// src/allEntities/performToolActionStep/PerformToolActionStep.tsx
import { push } from "connected-react-router";
import { Path } from "history";
import React from "react";
import { connect } from "react-redux";
import { PayloadActionCreator } from "typesafe-actions";
import {
  createAllEntities,
  deleteAllEntities,
  resetTransferCountsByEntityGroup,
} from "~/allEntities/allEntitiesActions";
import {
  includedCountsByEntityGroupSelector,
  pushAllChangesFetchStatusSelector,
  transferCountsByEntityGroupSelector,
} from "~/allEntities/allEntitiesSelectors";
import { toolActionSelector } from "~/app/appSelectors";
import { Flex, HelpDetails, NavigationButtonsRow } from "~/components";
import {
  CountsByEntityGroupModel,
  EntityGroup,
  FetchStatus,
  ReduxState,
  RoutePath,
  ToolAction,
} from "~/typeDefs";
import { capitalize, getEntityGroupDisplay } from "~/utils";
import ConfirmToolActionModal from "./ConfirmToolActionModal";
import ProgressBar from "./ProgressBar";

interface ConnectStateProps {
  pushAllChangesFetchStatus: FetchStatus;
  includedCountsByEntityGroup: CountsByEntityGroupModel;
  toolAction: ToolAction;
  transferCountsByEntityGroup: CountsByEntityGroupModel;
}

interface ConnectDispatchProps {
  onCreateAllEntities: PayloadActionCreator<string, void>;
  onDeleteAllEntities: PayloadActionCreator<string, void>;
  onPush: (path: Path) => void;
  onResetTransferCountsByEntityGroup: PayloadActionCreator<string, void>;
}

type Props = ConnectStateProps & ConnectDispatchProps;

export const PerformToolActionStepComponent: React.FC<Props> = props => {
  const [isConfirmModalOpen, setIsConfirmModalOpen] = React.useState<boolean>(
    false,
  );
  const [
    totalCountsByEntityGroup,
    setTotalCountsByEntityGroup,
  ] = React.useState<CountsByEntityGroupModel>({} as CountsByEntityGroupModel);

  React.useEffect(() => {
    props.onResetTransferCountsByEntityGroup();
    setTotalCountsByEntityGroup(props.includedCountsByEntityGroup);
  }, []);

  React.useEffect(() => {
    // TODO: Fix this so it shows if an error has occurred.
    if (props.pushAllChangesFetchStatus === FetchStatus.Success) {
      props.onPush(RoutePath.ToolActionSuccess);
    }
  }, [props.pushAllChangesFetchStatus]);

  const closeModal = (): void => setIsConfirmModalOpen(false);

  const handleBackClick = (): void => {
    props.onPush(RoutePath.SelectInclusions);
  };

  const handleNextClick = (): void => {
    setIsConfirmModalOpen(true);
  };

  const handleConfirmClick = (): void => {
    setIsConfirmModalOpen(false);
    switch (props.toolAction) {
      case ToolAction.Delete:
        props.onDeleteAllEntities();
        break;

      case ToolAction.Transfer:
        props.onCreateAllEntities();
        break;

      default:
        break;
    }
  };

  const title =
    props.toolAction === ToolAction.None
      ? "Perform Action"
      : `Perform ${capitalize(props.toolAction)} Action`;

  // If the records are being deleted, the order of entity groups processed is
  // in reverse (starts with time entries):
  const orderedEntityGroups =
    props.toolAction === ToolAction.Delete
      ? [
          EntityGroup.TimeEntries,
          EntityGroup.Tasks,
          EntityGroup.Projects,
          EntityGroup.Tags,
          EntityGroup.Clients,
        ]
      : Object.keys(totalCountsByEntityGroup);

  return (
    <section>
      <h1>Step 5: {title}</h1>
      <HelpDetails>
        <p>
          Press the <strong>Start</strong> button and confirm the action in the
          dialog.
        </p>
        <p>
          <strong>
            Note: this could take several minutes due to API rate limiting.
          </strong>
        </p>
      </HelpDetails>
      <Flex direction="column">
        {orderedEntityGroups.map(entityGroup => (
          <ProgressBar
            key={entityGroup}
            css={{ marginTop: 0 }}
            title={getEntityGroupDisplay(entityGroup as EntityGroup)}
            completedCount={props.transferCountsByEntityGroup[entityGroup]}
            totalCount={totalCountsByEntityGroup[entityGroup]}
          />
        ))}
      </Flex>
      <NavigationButtonsRow
        disabled={props.pushAllChangesFetchStatus === FetchStatus.InProcess}
        nextLabel="Start"
        onBackClick={handleBackClick}
        onNextClick={handleNextClick}
      />
      <ConfirmToolActionModal
        isOpen={isConfirmModalOpen}
        toolAction={props.toolAction}
        onClose={closeModal}
        onConfirm={handleConfirmClick}
      />
    </section>
  );
};

const mapStateToProps = (state: ReduxState): ConnectStateProps => ({
  pushAllChangesFetchStatus: pushAllChangesFetchStatusSelector(state),
  includedCountsByEntityGroup: includedCountsByEntityGroupSelector(state),
  toolAction: toolActionSelector(state),
  transferCountsByEntityGroup: transferCountsByEntityGroupSelector(state),
});

const mapDispatchToProps: ConnectDispatchProps = {
  onCreateAllEntities: createAllEntities.request,
  onDeleteAllEntities: deleteAllEntities.request,
  onPush: push,
  onResetTransferCountsByEntityGroup: resetTransferCountsByEntityGroup,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(PerformToolActionStepComponent);
