// src/clients/clientsInclusionsPanel/ClientsInclusionsPanel.tsx
import React from "react";
import { connect } from "react-redux";
import { PayloadActionCreator } from "typesafe-actions";
import {
  updateAreAllClientsIncluded,
  flipIsClientIncluded,
} from "~/clients/clientsActions";
import {
  clientsForInclusionsTableSelector,
  clientsTotalCountsByTypeSelector,
} from "~/clients/clientsSelectors";
import { EntityGroupInclusionsPanel } from "~/components";
import { ClientTableViewModel, EntityGroup, ReduxState } from "~/typeDefs";

interface ConnectStateProps {
  clients: ClientTableViewModel[];
  totalCountsByType: Record<string, number>;
}
interface ConnectDispatchProps {
  onFlipIsIncluded: PayloadActionCreator<string, string>;
  onUpdateAreAllIncluded: PayloadActionCreator<string, boolean>;
}

type Props = ConnectStateProps & ConnectDispatchProps;

export const ClientsInclusionsPanelComponent: React.FC<Props> = props => (
  <EntityGroupInclusionsPanel
    entityGroup={EntityGroup.Clients}
    rowNumber={1}
    tableData={props.clients}
    tableFields={[
      { label: "Name", field: "name" },
      { label: "Time Entry Count", field: "entryCount" },
      { label: "Project Count", field: "projectCount" },
    ]}
    totalCountsByType={props.totalCountsByType}
    onFlipIsIncluded={props.onFlipIsIncluded}
    onUpdateAreAllIncluded={props.onUpdateAreAllIncluded}
  />
);

const mapStateToProps = (state: ReduxState): ConnectStateProps => ({
  clients: clientsForInclusionsTableSelector(state),
  totalCountsByType: clientsTotalCountsByTypeSelector(state),
});

const mapDispatchToProps: ConnectDispatchProps = {
  onFlipIsIncluded: flipIsClientIncluded,
  onUpdateAreAllIncluded: updateAreAllClientsIncluded,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(ClientsInclusionsPanelComponent);

// src/steps/selectInclusionsStep/ClientsInclusionsPanel.svelte
<script lang="ts">
  import {
    updateAreAllClientsIncluded,
    flipIsClientIncluded,
  } from "~/modules/clients/clientsActions";
  import {
    clientsForInclusionsTableSelector,
    clientsTotalCountsByTypeSelector,
  } from "~/modules/clients/clientsSelectors";
  import { dispatchAction, selectorToStore } from "~/redux/reduxToStore";
  import { EntityGroup } from "~/typeDefs";

  import EntityGroupInclusionsPanel from "~/components/EntityGroupInclusionsPanel.svelte";

  const clients = selectorToStore(clientsForInclusionsTableSelector);

  const totalCountsByType = selectorToStore(clientsTotalCountsByTypeSelector);

  function handleToggleAll(event: CustomEvent<boolean>): void {
    dispatchAction(updateAreAllClientsIncluded(event.detail));
  }

  function handleToggleOne(event: CustomEvent<string>): void {
    dispatchAction(flipIsClientIncluded(event.detail));
  }
</script>

<EntityGroupInclusionsPanel
  entityGroup={EntityGroup.Clients}
  rowNumber={1}
  tableRecords={$clients}
  tableFields={[
    { label: "Name", field: "name" },
    { label: "Time Entry Count", field: "entryCount" },
    { label: "Project Count", field: "projectCount" },
  ]}
  totalCountsByType={$totalCountsByType}
  on:toggle-all={handleToggleAll}
  on:toggle-one={handleToggleOne}
/>
