// src/tags/tagsInclusionsPanel/TagsInclusionsPanel.tsx
import React from "react";
import { connect } from "react-redux";
import { PayloadActionCreator } from "typesafe-actions";
import {
  flipIsTagIncluded,
  updateAreAllTagsIncluded,
} from "~/tags/tagsActions";
import {
  tagsForInclusionsTableSelector,
  tagsTotalCountsByTypeSelector,
} from "~/tags/tagsSelectors";
import { EntityGroupInclusionsPanel } from "~/components";
import { EntityGroup, ReduxState, TableViewModel, TagModel } from "~/typeDefs";

interface ConnectStateProps {
  tags: TableViewModel<TagModel>[];
  totalCountsByType: Record<string, number>;
}

interface ConnectDispatchProps {
  onFlipIsIncluded: PayloadActionCreator<string, string>;
  onUpdateAreAllIncluded: PayloadActionCreator<string, boolean>;
}

type Props = ConnectStateProps & ConnectDispatchProps;

export const TagsInclusionsPanelComponent: React.FC<Props> = props => (
  <EntityGroupInclusionsPanel
    entityGroup={EntityGroup.Tags}
    rowNumber={2}
    tableData={props.tags}
    tableFields={[
      { label: "Name", field: "name" },
      { label: "Time Entry Count", field: "entryCount" },
    ]}
    totalCountsByType={props.totalCountsByType}
    onFlipIsIncluded={props.onFlipIsIncluded}
    onUpdateAreAllIncluded={props.onUpdateAreAllIncluded}
  />
);

const mapStateToProps = (state: ReduxState): ConnectStateProps => ({
  tags: tagsForInclusionsTableSelector(state),
  totalCountsByType: tagsTotalCountsByTypeSelector(state),
});

const mapDispatchToProps: ConnectDispatchProps = {
  onFlipIsIncluded: flipIsTagIncluded,
  onUpdateAreAllIncluded: updateAreAllTagsIncluded,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(TagsInclusionsPanelComponent);

// src/steps/selectInclusionsStep/TagsInclusionsPanel.svelte
<script lang="ts">
  import {
    updateAreAllTagsIncluded,
    flipIsTagIncluded,
  } from "~/modules/tags/tagsActions";
  import {
    tagsForInclusionsTableSelector,
    tagsTotalCountsByTypeSelector,
  } from "~/modules/tags/tagsSelectors";
  import { dispatchAction, selectorToStore } from "~/redux/reduxToStore";
  import { EntityGroup } from "~/typeDefs";

  import EntityGroupInclusionsPanel from "~/components/EntityGroupInclusionsPanel.svelte";

  const tags = selectorToStore(tagsForInclusionsTableSelector);

  const totalCountsByType = selectorToStore(tagsTotalCountsByTypeSelector);

  function handleToggleAll(event: CustomEvent<boolean>): void {
    dispatchAction(updateAreAllTagsIncluded(event.detail));
  }

  function handleToggleOne(event: CustomEvent<string>): void {
    dispatchAction(flipIsTagIncluded(event.detail));
  }
</script>

<EntityGroupInclusionsPanel
  entityGroup={EntityGroup.Tags}
  rowNumber={2}
  tableRecords={$tags}
  tableFields={[
    { label: "Name", field: "name" },
    { label: "Time Entry Count", field: "entryCount" },
  ]}
  totalCountsByType={$totalCountsByType}
  on:toggle-all={handleToggleAll}
  on:toggle-one={handleToggleOne}
/>
