// src/timeEntries/timeEntriesInclusionsPanel/TimeEntriesInclusionsTable.tsx
import format from "date-fns/format";
import React from "react";
import { PayloadActionCreator } from "typesafe-actions";
import {
  InclusionsTable,
  InclusionsTableCheckboxCell,
  InclusionsTableFoot,
  InclusionsTableRow,
} from "~/components";
import { TimeEntryTableViewModel } from "~/typeDefs";

const NullValueCell: React.FC<{ value: string | null }> = ({
  value,
  ...props
}) => (
  <td
    css={({ colors }) => ({
      color: `${value === null ? colors.manatee : colors.midnight} !important`,
      fontStyle: value === null ? "italic" : "normal",
    })}
    {...props}
  />
);

interface Props {
  timeEntries: TimeEntryTableViewModel[];
  totalCountsByType: Record<string, number>;
  onFlipIsIncluded: PayloadActionCreator<string, string>;
}

const TimeEntriesInclusionsTable: React.FC<Props> = props => (
  <InclusionsTable aria-labelledby="time-entries-desc">
    <thead>
      <tr>
        <th scope="col">Start Time</th>
        <th scope="col">End Time</th>
        <th scope="col">Task</th>
        <th scope="col">Project</th>
        <th scope="col" rowSpan={2} data-include={true}>
          Include?
        </th>
      </tr>
      <tr>
        <th scope="col" colSpan={3}>
          Description
        </th>
        <th scope="col">Tags</th>
      </tr>
    </thead>
    <tbody>
      {props.timeEntries.map(timeEntry => (
        <React.Fragment key={timeEntry.id}>
          <InclusionsTableRow disabled={timeEntry.existsInTarget}>
            <td>{format(timeEntry.start, "Pp")}</td>
            <td>{format(timeEntry.end, "Pp")}</td>
            <NullValueCell value={timeEntry.taskName}>
              {timeEntry.taskName ?? "None"}
            </NullValueCell>
            <NullValueCell value={timeEntry.projectName}>
              {timeEntry.projectName ?? "None"}
            </NullValueCell>
            <InclusionsTableCheckboxCell
              rowSpan={2}
              entityRecord={timeEntry}
              onFlipIsIncluded={props.onFlipIsIncluded}
            />
          </InclusionsTableRow>
          <InclusionsTableRow disabled={timeEntry.existsInTarget}>
            <td colSpan={3}>{timeEntry.description}</td>
            <td>{timeEntry.tagNames.join(", ")}</td>
          </InclusionsTableRow>
        </React.Fragment>
      ))}
    </tbody>
    <InclusionsTableFoot
      fieldCount={4}
      totalCountsByType={props.totalCountsByType}
    />
  </InclusionsTable>
);

export default TimeEntriesInclusionsTable;

// src/steps/selectInclusionsStep/TimeEntriesInclusionsTable.svelte
<script lang="ts">
  import format from "date-fns/format";
  import { createEventDispatcher } from "svelte";

  import type { TimeEntryTableViewModel } from "~/typeDefs";

  export let timeEntries: TimeEntryTableViewModel[];
  export let totalIncludedCount: number;

  const dispatchEvent = createEventDispatcher();

  function handleIncludeToggle(id: string): void {
    dispatchEvent("toggle", id);
  }
</script>

<style>
  td[data-disabled="true"] {
    color: var(--color-manatee);
  }

  td[data-null="true"] {
    color: var(--color-manatee);
    font-style: italic;
  }
</style>

<table>
  <thead>
    <tr>
      <th scope="col">Start Time</th>
      <th scope="col">End Time</th>
      <th scope="col">Task</th>
      <th scope="col">Project</th>
      <th scope="col" rowSpan={2} data-include={true}> Include? </th>
    </tr>
    <tr>
      <th scope="col" colSpan={3}> Description </th>
      <th scope="col">Tags</th>
    </tr>
  </thead>

  <tbody>
    {#each timeEntries as timeEntry}
      <tr>
        <td>{format(timeEntry.start, "Pp")}</td>
        <td>{format(timeEntry.end, "Pp")}</td>
        <td
          data-null={timeEntry.taskName === null}
          data-disabled={timeEntry.existsInTarget}
        >
          {timeEntry.taskName ?? "None"}
        </td>
        <td
          data-null={timeEntry.projectName === null}
          data-disabled={timeEntry.existsInTarget}
        >
          {timeEntry.projectName ?? "None"}
        </td>

        <td data-include rowspan={2}>
          <input
            type="checkbox"
            checked={timeEntry.existsInTarget ? false : timeEntry.isIncluded}
            disabled={timeEntry.existsInTarget}
            on:input={() => handleIncludeToggle(timeEntry.id)}
          />
        </td>
      </tr>

      <tr data-disabled={timeEntry.existsInTarget}>
        <td colspan={3}>{timeEntry.description}</td>
        <td>{timeEntry.tagNames.join(", ")}</td>
      </tr>
    {/each}
  </tbody>

  <tfoot>
    <tr>
      <th colspan={4}> Total </th>
      <td>{totalIncludedCount}</td>
    </tr>
  </tfoot>
</table>
