// src/components/ExternalLink.tsx
import React from "react";
import { styled } from "./emotion";

const openInNewTabPath = [
  "M432,320H400a16,16,0,0,0-16,16V448H64V128H208a16,16,0,0,0,16-16V80",
  "a16,16,0,0,0-16-16H48A48,48,0,0,0,0,112V464a48,48,0,0,0,48,48H400",
  "a48,48,0,0,0,48-48V336A16,16,0,0,0,432,320ZM488,0h-128",
  "c-21.37,0-32.05,25.91-17,41l35.73,35.73L135,320.37a24,24,0,0,0,0,34",
  "L157.67,377a24,24,0,0,0,34,0L435.28,133.32,471,169",
  "c15,15,41,4.5,41-17V24A24,24,0,0,0,488,0Z",
].join("");

/**
 * SVG icon taken from Font Awesome (`external-link-alt.svg`).
 * @see https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/external-link-alt.svg
 */
const openInNewTagSvg = `
<svg
  xmlns='http://www.w3.org/2000/svg'
  viewBox='0 0 512 512'
  height='12px'
  width='12px'
>
  <path d='${openInNewTabPath}' fill='steelblue' fill-opacity='1'></path>
</svg>
`;

const Link = styled.a({
  "&:after": {
    content: `url("data:image/svg+xml;utf8,${openInNewTagSvg}")`,
    margin: "0.25rem",
  },
});

const ExternalLink: React.FC<React.HTMLProps<HTMLAnchorElement>> = props => (
  <Link target="_blank" rel="noopener noreferrer" {...props} />
);

export default ExternalLink;

// src/components/ExternalLink.svelte
<script lang="ts">
  import clsx from "clsx";
  import { css } from "goober";

  type Variant = "light" | "dark";

  export let href: string;
  export let variant: Variant = "light";

  const { class: className, ...props } = $$restProps;

  const iconColor = variant === "light" ? "white" : "rgb(30,120,161)";
  const textColor = variant === "light" ? "white" : "primary";

  const styleClass = css`
    color: var(--color-${textColor});

    &::after {
      content: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512' height='12px' width='12px'> <path d='M432,320H400a16,16,0,0,0-16,16V448H64V128H208a16,16,0,0,0,16-16V80 a16,16,0,0,0-16-16H48A48,48,0,0,0,0,112V464a48,48,0,0,0,48,48H400 a48,48,0,0,0,48-48V336A16,16,0,0,0,432,320ZM488,0h-128 c-21.37,0-32.05,25.91-17,41l35.73,35.73L135,320.37a24,24,0,0,0,0,34 L157.67,377a24,24,0,0,0,34,0L435.28,133.32,471,169 c15,15,41,4.5,41-17V24A24,24,0,0,0,488,0Z' fill='${iconColor}' fill-opacity='1'></path></svg>");
      margin: 0.25rem;
    }
  `;
</script>

<a
  {href}
  rel="noopener noreferrer"
  target="_blank"
  class={clsx(styleClass, className)}
  {...props}
>
  <slot />
</a>
