// src/components/HelpDetails.svelte
<script lang="ts">
  import { css } from "goober";

  export let title: string = "Show/Hide Help";
  export let open: boolean = false;

  const styleClass = css`
    p {
      &:first-of-type {
        margin-top: 0;
        padding-top: 0;
      }

      &:not(:first-of-type) {
        margin-top: 0;
      }

      &:last-of-type {
        margin-bottom: 0;
      }
    }
  `;
</script>

<style>
  details {
    width: 100%;
    margin-bottom: 1rem;
    color: var(--color-primary);
  }

  div,
  summary {
    margin: 0;
    padding: 0.5rem 0.25rem;
  }

  div {
    margin: 0 1rem;
  }

  summary {
    cursor: default;
    font-weight: var(--font-weight-bold);
  }
</style>

<details class={styleClass} {open} {...$$restProps}>
  <summary>
    {title}
  </summary>

  <div>
    <slot />
  </div>

  <hr />
</details>

// src/components/HelpDetails.tsx
import React from "react";

import { styled } from "./emotion";

const Details = styled.details(
  {
    marginBottom: "1rem",
    width: "100%",

    "div,summary": {
      margin: 0,
      padding: "0.5rem 0.25rem",
    },

    p: {
      "&:not(first-of-type)": {
        marginTop: 0,
      },

      "&:last-of-type": {
        marginBottom: 0,
      },
    },
  },
  ({ theme }) => ({
    color: theme.colors.primary,
  }),
);

interface Props extends React.HTMLProps<HTMLDetailsElement> {
  title?: string;
}

const HelpDetails: React.FC<Props> = ({
  children,
  title = "Show/Hide Help",
  ...props
}) => (
  <Details {...props} as={undefined}>
    <summary css={(theme) => ({ fontWeight: theme.fontWeights.bold })}>
      {title}
    </summary>
    <div>{children}</div>
    <hr />
  </Details>
);

export default HelpDetails;
