// src/components/InclusionsTableTitle.tsx
import React from "react";

import Button from "./Button";
import { styled } from "./emotion";

const StyledDiv = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;

  button {
    padding: 0.25rem 0.5rem;
    border-radius: 0.25rem;
    font-size: 0.875rem;
    font-weight: var(--font-weight-bold);
  }
`;

interface Props extends React.HTMLProps<HTMLHeadingElement> {
  flipDisabled?: boolean;
  onFlipAreAllIncluded: VoidFunction;
}

const InclusionsTableTitle: React.FC<Props> = ({
  children,
  flipDisabled = false,
  onFlipAreAllIncluded,
  ...props
}) => {
  const handleIncludeButtonClick = (): void => {
    onFlipAreAllIncluded();
  };

  return (
    <StyledDiv>
      <h4 {...props}>{children}</h4>

      <Button
        disabled={flipDisabled}
        variant="outline"
        onClick={handleIncludeButtonClick}
      >
        Include All/None
      </Button>
    </StyledDiv>
  );
};

export default InclusionsTableTitle;

// src/components/InclusionsTableTitle.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  export let id: string;
  export let canToggleAll: boolean;

  const dispatchEvent = createEventDispatcher();

  function handleClick(): void {
    dispatchEvent("toggle-all");
  }
</script>

<style>
  div {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  button {
    height: fit-content;
    padding: 0.25rem 0.5rem;
    font-size: 0.875rem;
    border-radius: 0.25rem;
    font-weight: var(--font-weight-bold);
    background-color: var(--color-secondary);
    color: var(--color-primary);
    border: 3px solid var(--color-primary);
    transition: all 250ms linear;
  }

  button:active,
  button:focus {
    background-color: var(--color-active);
    color: var(--color-secondary);
    outline: 2px solid var(--color-secondary);
    transform: scale(1.05);
  }
</style>

<div {id}>
  <h4><slot /></h4>

  <button disabled={!canToggleAll} on:click={handleClick}>
    Include All/None
  </button>
</div>
