// src/credentials/enterCredentialsStep/ApiKeyInputField.tsx
import React from "react";
import * as R from "ramda";
import { styled, ExternalLink } from "~/components";
import { ToolHelpDetailsModel } from "~/app/appTypes";

const ErrorMessage = styled.div(
  {
    fontSize: "0.875rem",
    fontWeight: "bold",
    marginTop: "-0.75rem",
  },
  ({ theme }) => ({
    color: theme.colors.error,
  }),
);

const Input = styled.input({
  width: "100%",
  fontSize: "1rem",
  padding: "0.5rem",
  borderRadius: "0.25rem",
  borderStyle: "groove",
});

const Label = styled.label(
  {
    display: "block",
    fontSize: "1rem",
    margin: "0.5rem 0",
  },
  ({ theme }) => ({
    fontWeight: theme.fontWeights.bold,
  }),
);

interface Props extends React.InputHTMLAttributes<HTMLInputElement> {
  mapping: string;
  toolHelpDetails: ToolHelpDetailsModel;
  errorMessage?: string | null;
}

const ApiKeyInputField: React.FC<Props> = ({
  mapping,
  toolHelpDetails,
  errorMessage = null,
  ...props
}) => {
  const { displayName, toolLink } = toolHelpDetails;
  const errorId = `${mapping}-help-text`;
  return (
    <>
      <Label htmlFor={mapping}>
        {displayName} API Key (
        <ExternalLink href={toolLink}>
          find it on your {displayName} profile page
        </ExternalLink>
        )
      </Label>
      <Input
        id={mapping}
        name={mapping}
        type="text"
        autoComplete="hidden"
        aria-describedby={errorId}
        aria-invalid={!R.isNil(errorMessage).toString()}
        {...props}
      />
      {errorMessage && <ErrorMessage id={errorId}>{errorMessage}</ErrorMessage>}
    </>
  );
};

export default ApiKeyInputField;

// src/steps/enterApiKeysStep/ApiKeyInputField.svelte
<script lang="ts">
  import { slide } from "svelte/transition";

  import type { ToolHelpDetailsModel } from "~/typeDefs";

  import ExternalLink from "~/components/ExternalLink.svelte";

  export let mapping: string;
  export let toolHelpDetails: ToolHelpDetailsModel;
  export let errorMessage: string | null;
  export let value: string;

  const { toolName, displayName, toolLink } = toolHelpDetails;
</script>

<style>
  input {
    margin-bottom: 2rem;
    padding: 0.5rem;
    width: 100%;
    border: none;
    border-radius: 0.25rem;
    font-family: monospace;
    font-size: 1.25rem;
    box-shadow: var(--elevation-dp2);
  }

  label {
    display: block;
    margin: 0.5rem 0;
    font-size: 1rem;
    font-weight: var(--font-weight-bold);
  }

  [role="alert"] {
    display: block;
    margin-top: -1.5rem;
    color: var(--color-ruby);
    font-weight: var(--font-weight-bold);
  }
</style>

<div>
  <!-- prettier-ignore -->
  <label for={toolName}>
    {displayName} API Key (<ExternalLink href={toolLink} color="var(--color-navy)">find it on your {displayName} profile page</ExternalLink>)
  </label>

  <input
    id={toolName}
    name={mapping}
    type="text"
    autocomplete="off"
    aria-describedby="{toolName}-error"
    aria-required={true}
    aria-invalid={errorMessage !== null}
    bind:value
  />

  {#if errorMessage !== null}
    <span transition:slide={{ duration: 250 }} role="alert">
      {errorMessage}
    </span>
  {/if}
</div>
