// src/steps/selectInclusionsStep/ProjectsInclusionsPanel.svelte
<script lang="ts">
  import * as R from "ramda";

  import { toolActionSelector } from "~/modules/allEntities/allEntitiesSelectors";
  import {
    areAllProjectsIncludedUpdated,
    isProjectIncludedToggled,
  } from "~/modules/projects/projectsActions";
  import {
    projectsForInclusionsTableSelector,
    projectsTotalCountsByTypeSelector,
  } from "~/modules/projects/projectsSelectors";
  import { dispatchAction, selectorToStore } from "~/redux/reduxToStore";
  import { EntityGroup, ToolAction } from "~/typeDefs";

  import EntityGroupInclusionsPanel from "~/components/EntityGroupInclusionsPanel.svelte";

  const projects = selectorToStore(projectsForInclusionsTableSelector);

  const toolAction = selectorToStore(toolActionSelector);

  const totalCountsByType = selectorToStore(projectsTotalCountsByTypeSelector);

  // Only show the `isActiveInTarget` field if you're performing a transfer.
  // If the user is just deleting records, there is no "target":
  const tableFields = [
    { label: "Name", field: "name" },
    { label: "Time Entry Count", field: "entryCount" },
    { label: "Active in Source?", field: "isActiveInSource" },
  ];

  if ($toolAction === ToolAction.Transfer) {
    tableFields.push({ label: "Active in Target?", field: "isActiveInTarget" });
  }

  // Only show the total for active in target if performing a transfer,
  // otherwise the columns will be off by 1:
  let totalCountsByTypeToUse: Dictionary<number>;
  $: totalCountsByTypeToUse =
    $toolAction === ToolAction.Transfer
      ? $totalCountsByType
      : R.omit(["isActiveInTarget"], $totalCountsByType);

  function handleToggleAll(event: CustomEvent<boolean>): void {
    dispatchAction(areAllProjectsIncludedUpdated(event.detail));
  }

  function handleToggleOne(event: CustomEvent<string>): void {
    dispatchAction(isProjectIncludedToggled(event.detail));
  }
</script>

<EntityGroupInclusionsPanel
  entityGroup={EntityGroup.Projects}
  rowNumber={3}
  tableRecords={$projects}
  {tableFields}
  totalCountsByType={totalCountsByTypeToUse}
  on:toggle-all={handleToggleAll}
  on:toggle-one={handleToggleOne}
/>

// src/pages/selectInclusionsStep/ProjectsInclusionsPanel.tsx
import * as R from "ramda";
import React from "react";
import { connect } from "react-redux";
import { PayloadActionCreator } from "typesafe-actions";

import { EntityGroupInclusionsPanel } from "~/components";
import { toolActionSelector } from "~/modules/allEntities/allEntitiesSelectors";
import {
  flipIsProjectIncluded,
  updateAreAllProjectsIncluded,
} from "~/modules/projects/projectsActions";
import {
  projectsForInclusionsTableSelector,
  projectsTotalCountsByTypeSelector,
} from "~/modules/projects/projectsSelectors";
import {
  EntityGroup,
  ProjectModel,
  ReduxState,
  TableViewModel,
  ToolAction,
} from "~/typeDefs";

interface ConnectStateProps {
  projects: TableViewModel<ProjectModel>[];
  toolAction: ToolAction;
  totalCountsByType: Record<string, number>;
}

interface ConnectDispatchProps {
  onFlipIsIncluded: PayloadActionCreator<string, string>;
  onUpdateAreAllIncluded: PayloadActionCreator<string, boolean>;
}

type Props = ConnectStateProps & ConnectDispatchProps;

export const ProjectsInclusionsPanelComponent: React.FC<Props> = (props) => {
  // Only show the `isActiveInTarget` field if you're performing a transfer.
  // If the user is just deleting records, there is no "target":
  const tableFields = [
    { label: "Name", field: "name" },
    { label: "Time Entry Count", field: "entryCount" },
    { label: "Active in Source?", field: "isActiveInSource" },
  ];

  if (props.toolAction === ToolAction.Transfer) {
    tableFields.push({ label: "Active in Target?", field: "isActiveInTarget" });
  }

  // Only show the total for active in target if performing a transfer,
  // otherwise the columns will be off by 1:
  const totalCountsByType =
    props.toolAction === ToolAction.Transfer
      ? props.totalCountsByType
      : R.omit(["isActiveInTarget"], props.totalCountsByType);

  return (
    <EntityGroupInclusionsPanel
      entityGroup={EntityGroup.Projects}
      rowNumber={3}
      tableData={props.projects}
      tableFields={tableFields}
      totalCountsByType={totalCountsByType}
      onFlipIsIncluded={props.onFlipIsIncluded}
      onUpdateAreAllIncluded={props.onUpdateAreAllIncluded}
    />
  );
};

const mapStateToProps = (state: ReduxState): ConnectStateProps => ({
  projects: projectsForInclusionsTableSelector(state),
  toolAction: toolActionSelector(state),
  totalCountsByType: projectsTotalCountsByTypeSelector(state),
});

const mapDispatchToProps: ConnectDispatchProps = {
  onUpdateAreAllIncluded: updateAreAllProjectsIncluded,
  onFlipIsIncluded: flipIsProjectIncluded,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(ProjectsInclusionsPanelComponent);
