// src/steps/selectInclusionsStep/TimeEntriesInclusionsPanel.svelte
<script lang="ts">
  import { replaceMappingWithToolName } from "~/entityOperations/replaceMappingWithToolName";
  import { toolActionSelector } from "~/modules/allEntities/allEntitiesSelectors";
  import {
    flipIsTimeEntryIncluded,
    updateAreAllTimeEntriesIncluded,
    flipIsDuplicateCheckEnabled,
  } from "~/modules/timeEntries/timeEntriesActions";
  import {
    isDuplicateCheckEnabledSelector,
    timeEntriesForInclusionsTableSelector,
    timeEntriesTotalCountsByTypeSelector,
  } from "~/modules/timeEntries/timeEntriesSelectors";
  import { dispatchAction, selectorToStore } from "~/redux/reduxToStore";
  import { type TimeEntryTableViewModel, ToolAction } from "~/typeDefs";

  import AccordionPanel from "~/components/AccordionPanel.svelte";
  import InclusionsTableTitle from "~/components/InclusionsTableTitle.svelte";
  import NoRecordsFound from "~/components/NoRecordsFound.svelte";
  import Toggle from "~/components/Toggle.svelte";

  import TimeEntriesInclusionsTable from "./TimeEntriesInclusionsTable.svelte";
  import TimeEntryComparisonDisclaimer from "./TimeEntryComparisonDisclaimer.svelte";

  const isCheckDuplicates = selectorToStore(isDuplicateCheckEnabledSelector);

  const timeEntries = selectorToStore(timeEntriesForInclusionsTableSelector);

  const toolAction = selectorToStore(toolActionSelector);

  const totalCountsByType = selectorToStore(
    timeEntriesTotalCountsByTypeSelector,
  );

  let recordCount: number;
  $: recordCount = $timeEntries.length === 0 ? $timeEntries.length : 1;

  let areAllToggled: boolean;
  $: areAllToggled =
    $totalCountsByType.isIncluded + $totalCountsByType.existsInTarget ===
    recordCount;

  let nonExistingRecords: TimeEntryTableViewModel[];
  $: nonExistingRecords = $timeEntries.filter(
    ({ existsInTarget }) => !existsInTarget,
  );

  function handleToggleAll(): void {
    dispatchAction(updateAreAllTimeEntriesIncluded(!areAllToggled));
  }

  function handleToggleOne(event: CustomEvent<string>): void {
    dispatchAction(flipIsTimeEntryIncluded(event.detail));
  }

  function handleToggleUseDuplicate(): void {
    dispatchAction(flipIsDuplicateCheckEnabled());
  }
</script>

<style>
  label {
    margin-bottom: 0.75rem;
    font-weight: var(--font-weight-bold);
  }
</style>

<AccordionPanel rowNumber={5} title="Time Entries">
  {#if recordCount === 0}
    <NoRecordsFound />
  {:else}
    {#if $toolAction === ToolAction.Transfer}
      <TimeEntryComparisonDisclaimer />

      <div style="margin-bottom: 0.75rem;">
        <label for="use-duplicate-check-toggle"
          >Use the time entry duplication check?</label
        >

        <Toggle
          id="use-duplicate-check-toggle"
          style="background-color: var(--color-white);"
          toggled={$isCheckDuplicates}
          on:toggle={handleToggleUseDuplicate}
        />
      </div>
    {/if}

    <InclusionsTableTitle
      id="time-entries-title"
      canToggleAll={nonExistingRecords.length !== 0}
      on:toggle-all={handleToggleAll}
    >
      {replaceMappingWithToolName("Time Entry Records in Source")}
    </InclusionsTableTitle>

    <TimeEntriesInclusionsTable
      timeEntries={$timeEntries}
      totalCountsByType={$totalCountsByType}
      on:toggle={handleToggleOne}
    />
  {/if}
</AccordionPanel>

// src/pages/selectInclusionsStep/TimeEntriesInclusionsPanel.tsx
import React from "react";
import { connect } from "react-redux";
import { PayloadActionCreator, EmptyActionCreator } from "typesafe-actions";

import {
  AccordionPanel,
  InclusionsTableTitle,
  NoRecordsFound,
} from "~/components";
import {
  replaceMappingWithToolNameSelector,
  toolActionSelector,
} from "~/modules/allEntities/allEntitiesSelectors";
import {
  flipIsTimeEntryIncluded,
  updateAreAllTimeEntriesIncluded,
  flipIsDuplicateCheckEnabled,
} from "~/modules/timeEntries/timeEntriesActions";
import {
  timeEntriesForInclusionsTableSelector,
  timeEntriesTotalCountsByTypeSelector,
  isDuplicateCheckEnabledSelector,
} from "~/modules/timeEntries/timeEntriesSelectors";
import { ReduxState, TimeEntryTableViewModel, ToolAction } from "~/typeDefs";

import DuplicateCheckToggle from "./DuplicateCheckToggle";
import TimeEntriesInclusionsTable from "./TimeEntriesInclusionsTable";
import TimeEntryComparisonDisclaimer from "./TimeEntryComparisonDisclaimer";

interface ConnectStateProps {
  isDuplicateCheckEnabled: boolean;
  replaceMappingWithToolName: (label: string) => string;
  timeEntries: TimeEntryTableViewModel[];
  toolAction: ToolAction;
  totalCountsByType: Record<string, number>;
}

interface ConnectDispatchProps {
  onFlipIsDuplicateCheckEnabled: EmptyActionCreator<string>;
  onFlipIsIncluded: PayloadActionCreator<string, string>;
  onUpdateAreAllIncluded: PayloadActionCreator<string, boolean>;
}

type Props = ConnectStateProps & ConnectDispatchProps;

export const TimeEntriesInclusionsPanelComponent: React.FC<Props> = ({
  timeEntries,
  ...props
}) => {
  const { isIncluded, existsInTarget } = props.totalCountsByType;
  const recordCount = timeEntries.length !== 0 ? timeEntries.length : 1;
  const areAllToggled = isIncluded + existsInTarget === recordCount;

  const handleFlipInclusions = (): void => {
    props.onUpdateAreAllIncluded(!areAllToggled);
  };

  const nonExistingRecords = timeEntries.filter(
    ({ existsInTarget }) => !existsInTarget,
  );

  return (
    <AccordionPanel rowNumber={5} title="Time Entries">
      {recordCount === 0 ? (
        <NoRecordsFound />
      ) : (
        <>
          {props.toolAction === ToolAction.Transfer && (
            <>
              <TimeEntryComparisonDisclaimer />
              <DuplicateCheckToggle
                onToggle={props.onFlipIsDuplicateCheckEnabled}
                isToggled={props.isDuplicateCheckEnabled}
              />
            </>
          )}
          <InclusionsTableTitle
            id="time-entries-desc"
            flipDisabled={nonExistingRecords.length === 0}
            onFlipAreAllIncluded={handleFlipInclusions}
          >
            {props.replaceMappingWithToolName("Time Entry Records in Source")}
          </InclusionsTableTitle>
          <TimeEntriesInclusionsTable
            isDuplicateCheckEnabled={props.isDuplicateCheckEnabled}
            timeEntries={timeEntries}
            totalCountsByType={props.totalCountsByType}
            onFlipIsIncluded={props.onFlipIsIncluded}
          />
        </>
      )}
    </AccordionPanel>
  );
};

const mapStateToProps = (state: ReduxState): ConnectStateProps => ({
  isDuplicateCheckEnabled: isDuplicateCheckEnabledSelector(state),
  replaceMappingWithToolName: replaceMappingWithToolNameSelector(state),
  timeEntries: timeEntriesForInclusionsTableSelector(state),
  toolAction: toolActionSelector(state),
  totalCountsByType: timeEntriesTotalCountsByTypeSelector(state),
});

const mapDispatchToProps: ConnectDispatchProps = {
  onFlipIsDuplicateCheckEnabled: flipIsDuplicateCheckEnabled,
  onFlipIsIncluded: flipIsTimeEntryIncluded,
  onUpdateAreAllIncluded: updateAreAllTimeEntriesIncluded,
};

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(TimeEntriesInclusionsPanelComponent);
