// src/steps/pickToolActionStep/ToolActionCard.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  import type { ToolAction, ToolName } from "~/typeDefs";

  import Button from "~/components/Button.svelte";
  import Card from "~/components/Card.svelte";

  export let action: ToolAction;
  export let title: string;
  export let source: ToolName;
  export let target: ToolName;

  const dispatchEvent = createEventDispatcher();

  function handleClick(): void {
    dispatchEvent("select", { action, source, target });
  }
</script>

<style>
  p {
    margin: 0 0 2rem;
  }
</style>

<Card {title}>
  <p><slot /></p>

  <Button
    variant="secondary"
    style="margin-top: auto; width: fit-content;"
    on:click={handleClick}
  >
    Select
  </Button>
</Card>

// src/app/pickToolActionStep/ToolActionCard.tsx
import React from "react";
import { Button, Card } from "~/components";
import { ToolAction, ToolName } from "~/typeDefs";

interface Props {
  action: ToolAction;
  header: React.ReactNode;
  source: ToolName;
  target: ToolName;
  onSelectClick: (
    action: ToolAction,
    source: ToolName,
    target: ToolName,
  ) => void;
}

const ToolActionCard: React.FC<Props> = ({
  action,
  children,
  header,
  source,
  target,
  onSelectClick,
  ...props
}) => (
  <Card title={header} {...props}>
    <p css={{ margin: "0 0 2rem 0" }}>{children}</p>
    <Button
      css={{ marginTop: "auto", width: "fit-content" }}
      variant="secondary"
      onClick={() => onSelectClick(action, source, target)}
    >
      Select
    </Button>
  </Card>
);

export default ToolActionCard;
