// src/app/appRoot/Footer.tsx
import React from "react";
import {
  ExternalLink,
  Flex,
  Icon,
  IconLink,
  styled,
  VisuallyHidden,
} from "~/components";

const Base = styled.footer(
  {
    display: "flex",
    height: "7rem",
    justifyContent: "space-between",
    padding: "2rem",
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,

    a: {
      textDecoration: "underline",
    },

    p: {
      margin: 0,
    },
  },
  ({ theme }) => ({
    background: theme.colors.primary,
    color: theme.colors.secondary,

    [theme.query.mobile]: {
      justifyContent: "center",
    },

    [theme.query.small]: {
      fontSize: 14,
    },

    "a:focus": {
      outlineColor: theme.colors.secondary,
    },
  }),
);

const RightColumn = styled.div({
  fontWeight: 500,
  textAlign: "right",

  "@media (max-width: 32rem)": {
    display: "none",
  },
});

const SocialLinksNav = styled.nav(
  {
    marginTop: "0.25rem",
  },
  ({ theme }) => ({
    [theme.query.mobile]: {
      display: "flex",
      justifyContent: "center",
    },
  }),
);

const Love: React.FC = () => <Icon name="heart" color="ruby" height={12} />;

const LinkToMe: React.FC = () => (
  <ExternalLink color="white" href="https://github.com/mikerourke">
    Mike Rourke
  </ExternalLink>
);

const LinkToIssues: React.FC = () => (
  <ExternalLink
    color="white"
    href="https://github.com/mikerourke/transfermyti.me/issues"
  >
    in the GitHub repository
  </ExternalLink>
);

const Footer: React.FC = () => (
  <Base>
    <div>
      <p>
        Made with
        <Love />
        by <LinkToMe /> © {new Date().getFullYear()}
      </p>
      <SocialLinksNav aria-labelledby="footer-social-links">
        <VisuallyHidden id="footer-social-links">
          Social Media Links
        </VisuallyHidden>
        <Flex
          as="ul"
          id="footer-social-links"
          css={{ listStyle: "none", padding: 0 }}
        >
          <li css={{ marginRight: "1rem" }}>
            <IconLink
              href="https://github.com/mikerourke"
              iconName="github"
              color="white"
            >
              GitHub
            </IconLink>
          </li>
          <li css={{ marginRight: "1rem" }}>
            <IconLink
              href="https://www.linkedin.com/in/michaelwrourke"
              iconName="linkedIn"
              color="white"
            >
              LinkedIn
            </IconLink>
          </li>
          <li>
            <IconLink
              href="https://twitter.com/codelikeawolf"
              iconName="twitter"
              color="white"
            >
              Twitter
            </IconLink>
          </li>
        </Flex>
      </SocialLinksNav>
    </div>
    <RightColumn>
      <p>The time tracking tool companies are not responsible for this tool.</p>
      <p>
        Please file any issues <LinkToIssues />.
      </p>
    </RightColumn>
  </Base>
);

export default Footer;

// src/layout/Footer.svelte
<script lang="ts">
  import { css } from "goober";

  import ExternalLink from "~/components/ExternalLink.svelte";
  import Icon from "~/components/Icon.svelte";
  import IconLink from "~/components/IconLink.svelte";

  const iconSize = { height: 18, width: 18 };

  const styleClass = css`
    a {
      color: var(--color-white);
      text-decoration: underline;
    }

    ul li a {
      &:active,
      &:focus {
        outline: none;

        path {
          fill: var(--color-active);
        }
      }
    }
  `;
</script>

<style>
  footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    position: fixed;
    bottom: 0;
    left: 0;
    right: 0;
    height: var(--height-footer);
    padding: 0 2rem;
    background-color: var(--color-primary);
    color: var(--color-secondary);
  }

  p {
    margin: 0;
    font-size: 0.9rem;
  }

  nav {
    margin-top: 0.25rem;
  }

  ul,
  li {
    padding: 0;
  }

  ul {
    display: flex;
    gap: 1rem;
  }

  li {
    list-style: none;
  }

  footer div:last-of-type {
    text-align: right;
    font-weight: 500;
  }

  @media (max-width: 32rem) {
    footer {
      justify-content: center;
    }

    nav {
      display: flex;
      justify-content: center;
    }

    footer div:last-of-type {
      display: none;
    }
  }

  @media (min-width: 33rem) and (max-width: 52rem) {
    footer {
      font-size: 14px;
    }
  }
</style>

<footer class={styleClass}>
  <div>
    <p>
      Made with <Icon name="heart" color="var(--color-ruby)" height={12} />
      by <ExternalLink href="https://mikerourke.dev">Mike Rourke</ExternalLink>
      © {new Date().getFullYear()}
    </p>

    <nav aria-label="Social Media Links">
      <ul>
        <li>
          <IconLink
            aria-label="GitHub Profile"
            iconName="github"
            href="https://github.com/mikerourke"
            {...iconSize}
          />
        </li>

        <li>
          <IconLink
            aria-label="LinkedIn Profile"
            iconName="linkedIn"
            href="https://www.linkedin.com/in/michaelwrourke"
            {...iconSize}
          />
        </li>

        <li>
          <IconLink
            aria-label="Twitter Profile"
            iconName="twitter"
            href="https://twitter.com/codelikeawolf"
            {...iconSize}
          />
        </li>
      </ul>
    </nav>
  </div>

  <div>
    <p>The time tracking tool companies are not responsible for this tool.</p>

    <!-- prettier-ignore -->
    <p>
      Please file any issues
      <ExternalLink href="https://github.com/mikerourke/transfermyti.me/issues">in the GitHub repository</ExternalLink>.
    </p>
  </div>
</footer>
