// src/layout/Header.tsx
import React from "react";
import { Link } from "react-router-dom";

import { styled } from "~/components";
import Logo from "~/layout/Logo";
import { RoutePath } from "~/typeDefs";

const StyledHeader = styled.header`
  display: flex;
  align-items: center;
  height: 3rem;
  width: 100%;
  padding: 0 1rem;
  background-color: var(--color-primary);
  color: var(--color-secondary);

  a {
    color: var(--color-secondary);
    font-size: 1.5rem;
  }
`;

const Header: React.FC = () => (
  <StyledHeader>
    <Logo />

    <Link to={RoutePath.PickToolAction}>transfermyti.me</Link>
  </StyledHeader>
);

export default Header;

// src/layout/Header.svelte
<script lang="ts">
  import { Link } from "svelte-routing";

  import { RoutePath } from "~/typeDefs";

  import Logo from "~/layout/Logo.svelte";

  function getProps(): Dictionary<unknown> {
    return { style: "color: var(--color-secondary); font-size: 1.5rem;" };
  }
</script>

<style>
  header {
    display: flex;
    align-items: center;
    height: var(--height-header);
    padding: 0 1rem;
    width: 100%;
    background-color: var(--color-primary);
    color: var(--color-secondary);
  }
</style>

<header>
  <Logo />

  <Link to={RoutePath.PickToolAction} {getProps}>transfermyti.me</Link>
</header>
