// src/app/appRoot/Header.tsx
import React from "react";
import { Link } from "react-router-dom";

import Logo from "./Logo";
import { styled } from "~/components";
import { RoutePath } from "~/typeDefs";

const Base = styled.header(
  {
    alignItems: "center",
    display: "flex",
    height: "3rem",
    padding: "0 1rem",
    width: "100%",
  },
  ({ theme }) => ({
    background: theme.colors.primary,
    color: theme.colors.secondary,
  }),
);

const Header: React.FC = () => (
  <Base>
    <Logo />
    <Link
      css={(theme) => ({ color: theme.colors.secondary, fontSize: "1.5rem" })}
      to={RoutePath.PickToolAction}
    >
      transfermyti.me
    </Link>
  </Base>
);

export default Header;

// src/layout/Header.svelte
<script lang="ts">
  import { Link } from "svelte-routing";

  import { RoutePath } from "~/typeDefs";

  import Logo from "~/layout/Logo.svelte";

  function getProps(): Dictionary<unknown> {
    return { style: "color: var(--color-secondary); font-size: 1.5rem;" };
  }
</script>

<style>
  header {
    display: flex;
    align-items: center;
    height: var(--height-header);
    padding: 0 1rem;
    width: 100%;
    background-color: var(--color-primary);
    color: var(--color-secondary);
  }
</style>

<header>
  <Logo />

  <Link to={RoutePath.PickToolAction} {getProps}>transfermyti.me</Link>
</header>
