// src/layout/NotificationToast.svelte
<script lang="ts">
  import { css } from "goober";
  import { onMount } from "svelte";

  import { dismissNotification } from "~/modules/app/appActions";
  import { dispatchAction } from "~/redux/reduxToStore";
  import type { NotificationModel } from "~/typeDefs";

  import Icon from "~/components/Icon.svelte";

  export let notification: NotificationModel;

  onMount(() => {
    setTimeout(dismiss, 5_000);
  });

  function dismiss(): void {
    dispatchAction(dismissNotification(notification.id));
  }

  const buttonStyleClass = css`
    position: absolute;
    top: 0.375rem;
    right: 0.5rem;
    margin: 0;
    padding: 0;
    background-color: transparent;
    color: var(--color-white);
    line-height: 1;

    path {
      fill: var(--color-white);
      stroke: var(--color-white);
    }

    &:hover path {
      stroke: var(--color-white);
      stroke-width: 4;
      transition: all var(--duration-short) var(--transition-function);
    }
  `;
</script>

<style>
  [role="status"] {
    position: relative;
    display: flex;
    gap: 1rem;
    width: 20rem;
    margin: 1rem 0.5rem 0 0;
    padding: 1rem;
    border-radius: 0.375rem;
    color: var(--color-white);
    font-weight: var(--font-weight-medium);
    box-shadow: var(--elevation-dp2);
    letter-spacing: -0.375px;
    z-index: var(--z-index-notification);
  }

  .error {
    background-color: var(--color-ruby);
  }

  .success {
    background-color: var(--color-green);
  }
</style>

<div
  role="status"
  class:error={notification.type === "error"}
  class:success={notification.type === "success"}
>
  {notification.message}

  <button
    class={buttonStyleClass}
    aria-label="Dismiss the notification"
    on:click={dismiss}
  >
    <Icon name="close" color="var(--color-secondary)" width={18} height={18} />
  </button>
</div>

// src/layout/NotificationToast.tsx
import React from "react";
import type { TransitionStatus } from "react-transition-group/Transition";

import { styled, useTheme } from "~/components";
import type { NotificationModel } from "~/typeDefs";

const StyledDiv = styled.div`
  position: absolute;
  right: 1rem;
  width: 20rem;
  padding: 1rem;
  border: none;
  border-radius: 0.375rem;
  transition: top 500ms ease-out;
  background-color: var(--color-midnight);
  box-shadow: var(--elevation-dp4);
  color: var(--color-white);
  height: var(--height-notification);
  z-index: var(--z-index-notification);

  span {
    position: absolute;
    bottom: 2.25rem;
    right: -1.375rem;
    height: 0;
    width: 0;
    border-style: solid;
    border-width: 1.5rem 1rem 0;
    border-color: var(--color-midnight) transparent transparent transparent;
    pointer-events: none;
    transform: rotate(270deg);
  }
`;

interface Props {
  index: number;
  notification: NotificationModel;
  transitionStatus: TransitionStatus;
  onDismissNotification: (notificationId: string) => void;
}

const NotificationToast: React.FC<Props> = ({
  index,
  notification,
  transitionStatus,
  onDismissNotification,
  ...props
}) => {
  const { sizes } = useTheme();

  React.useEffect(() => {
    setTimeout(() => {
      onDismissNotification(notification.id);
    }, 5_000);
  }, []);

  // @ts-ignore
  const animation = {
    entering: `slide-in-right 300ms 1 linear both`,
    exiting: `slide-out-left 600ms 1 linear both`,
  }[transitionStatus];

  // Height of notification plus 1rem for bottom padding:
  const topRems = index * (sizes.notificationHeight + sizes.notificationGap);

  return (
    <StyledDiv
      role="status"
      style={{ animation, top: `${topRems}rem` }}
      {...props}
    >
      {notification.message}

      <span />
    </StyledDiv>
  );
};

export default NotificationToast;
